[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "simple-git-gui"
version = "0.1.0"
description = "A simple PyQt6-based Git GUI"
authors = [
  { name="Your Name", email="you@example.com" }
]
dependencies = [
  "PyQt6",
  "requests",
  "appdirs"
]
